/**
 * Collection of places
 */
export const PlaceTypes = [
    "in the city",
    "in a store",
    "at the school",
    "in space",
    "moon",
    "inside a cave",
    "inside a house",
    "in the bathroom",
    "inside a church",
    "outside a motel",
    "on the street",
    "at the beach",
    "at the forest",
    "at the river",
    "in the game store",
    "at the zoo",
    "at the gym",
    "in jell",
    "at the park",
    "sky",
    "inside the ocean",
    "at the stadium",
    "at the laboratory",
    "at the restaurant",
    "inside a box",
    "at the party",
    "at the disco",
    "at the dungeon",
    "inside a jar",
    "at the mountains",
    "on a rooftop",
    "top of a building",
    "at the amusement park",
    "in autumn",
    "sun flower field",
    "at the flower shop",
    "at the comfy living room",
    "outer space",
    "at the arcade game",
    "at the cafe",
    "cityscape",
    "at the classroom",
    "in a desert",
    "in a indoor pool",
    "landscape",
    "magic circle",
    "at the pool",
    "rain",
    "in a ruins",
    "shooting star",
    "snow",
    "at the vending machine",
    "at the waterfall",
    "vegetation",
    "cyberpunk",
    "in a dark alley",
    "at the office",
    "on the bed",
    "on bus",
    "in a train",
    "heart background"
];
/**
 * Collection of times
 */
export const TimeTypes = [
    "night",
    "evening",
    "morning",
    "sunrise",
    "afternoon",
    "sunset",
    "morning"
]