/**
 * Body view types
 */
export const BodyViewTypes = [
    "full body",
    "only feet",
    "face only",
];
/**
 * Body poses types
 */
export const BodyPosesTypes = [
    "standing",
    "against a wall",
    "sitting",
    "leaning forward",
    "resting head in her arms",
    "sitting",
    "crossing arms",
    "hand on hip",
    "twirl",
    "leaning",
    "throwing",
    "hug",
    "jumping",
    "kissing",
    "walking",
    "crossed legs",
    "fighting stance",
    "running",
    "yokozuwari",
    "twisted torso",
    "look back",
    "ass focus",
    "between legs",
    "breast focus",
    "crawling",
    "crossed legs",
    "hands over",
    "head tilt",
    "kneeling",
    'leg lift',
    "leg up",
    "lying on stomach",
    "squatting",
    "squatting, ass focus",
    "thigh straddling",
    "showing panties",
    "selfie",
    "leaning",
    "spread arms"
]
/**
 * Body accessories types
 */
export const BodyAccessoriesTypes = [
    "guitar",
    "purse",
    "necklace",
    "belt",
    "scarf",
    "gloves",
    "baseball bat",
    "gun",
    "sword",
    "cellphone",
    "book",
    "soccer ball",
    "laptop",
    "pencil",
    "tie",
    "bomb",
    "money",
    "dildo",
    "papers",
    "water bottle",
    "apple",
    "orange",
    "carrot",
    "boxing gloves",
    "watch",
    "case",
    "game console",
    "spoon",
    "bucket",
    "laser sword",
    "fire sword",
    "rocket launcher",
    "flowers",
    "gift",
    "bag of food",
    "backpack",
    "tattoos",
    "cat tail",
    "fox tail",
    "dragon wings",
    "wings",
    "chicken wings",
    "bat wings",
    "tail",
    "dragon tail",
    "camera",
    "chair",
    "dagger",
    "handgun",
    "ice cream",
    "microphone",
    "piano",
    "wine glass",
    "ring",
    "dakimakura",
    "nendroid"
];
/**
 * Body proportions types
 */
export const BodyProportionsTypes = [
    "plus size breasts",
    "very small breasts",
    "extra large breast",
    "flat chest",
    "very small breasts",
    "extra large breasts",
    "fat",
    "cleavage",
    "large breast",
    "pregnant",
    "skinny",
    "plus size torso",
    "plus size legs",
    "small breasts",
    "muscular"
];
/**
 * Body costume types
 */
export const BodyCostumeTypes = [
    "pink white short sexy apron",
    "white lace",
    "sexy lingerie",
    "beautiful detailed sexy underwear",
    "armored dress",
    "backless outfit",
    "bandeau",
    "kimono",
    "yukata",
    "bikini",
    "bunny girl",
    "chinese clothes",
    "dress",
    "fur jacket",
    "hakama",
    "latex suit",
    "leotard",
    "maid apron",
    "micro bikini",
    "bikini",
    "mobile latex suit",
    "office suit",
    "pink strapless dress",
    "sailor dress",
    "school swimsuit",
    "school uniform",
    "soldier commander uniform",
    "soldier uniform",
    "nurse uniform",
    "suit",
    "suspender skirt",
    "swimsuits",
    "transparent latex suit",
    "tribal",
    "stripe pajamas",
    "wafuku",
    "wedding dress",
    "nude",
    "blouse",
    "cheerleader",
    "secretary",
    "leotard"
];
/**
 * Body gender types
 */
export const BodyGenderTypes = [
    "shota",
    "loli",
    "feminine boy",
    "old woman",
    "teenage",
    "student",
    "milf",
    "man",
    "woman",
    "boy",
    "girl",
    "kawaii",
    "mature female",
    "old man",
    "tom girl",
    "crossdressing"
]