/**
 * Theme types list
 */
export const ThemeTypes = [
    "pokemon girl",
    "safeguard",
    "amazon",
    "space girl",
    "monster hunter",
    "pokemon",
    "mario bros",
    "mario girl",
    "kirby",
    "luigi girl",
    "luigi boy",
    "halloween",
    "christmas",
    "easter egg",
    "dead",
    "killer",
    "dancing",
    "pikachu",
    "charmander",
    "charizard",
    "genshin impact",
    "raiden",
    "mona",
    "klee",
    "programmer",
    "jesus",
    "worker",
    "nurse",
    "sponge bob",
    "patrick star",
    "streamer girl",
    "likes bald dudes",
    "is crazy for cats",
    "cats everywhere",
    "animal everywhere",
    "this girl is on fire",
]