/**
 * Face expression types
 */
export const FaceExpressionTypes = [
    "fear",
    "sad",
    "confused",
    "silly",
    "serious",
    "drunk",
    "rage",
    "disgusted",
    "blush",
    "happy",
    "angry",
    "crying",
    "love",
    "very angry",
    "flirty",
    "pleased",
    "laughing",
    "crying, smile",
    "sleepy",
    "screaming",
    "surprised",
    'annoyed',
    "clenched teeth",
    "evil smile",
    "fang",
    "food on",
    "frown",
    "hands cover mouth",
    "licking lips",
    "mouth hold",
    "naughty",
    "one eye closed",
    "pain",
    "tongue",
    "yandere",
    "worried"
]
/**
 * Face accessory types
 */
export const FaceAccessoryTypes = [
    "glasses",
    "sunglasses",
    "eye patch",
    "monocle",
    "headband",
    "bandana",
    "scarf",
    "mask",
    "piercings",
    "earrings",
    "nose ring",
    "lip ring",
    "chin strap",
    "beard",
    "mustache",
    "earrings",
    "elf",
    "cow ears",
    "monkey ears",
    "sheep ears",
    "elf",
    "gas mask",
    "goggles",
    "mask",
    "makeup"
]