/**
 * Collection of head type accessories
 */
export const HeadAccessoriesTypes = [
    "cat ears",
    "dog ears",
    "witch hat",
    "crown",
    "bear hat",
    "flower ornament",
    "beanie",
    "cap",
    "helmet",
    "top hat",
    "straw hat",
    "beret",
    "rabbit ears",
    "party hat",
    "cowboy hat",
    "chef hat",
    "dragon horns",
    "demon horns",
    "unicorn horn",
    "hat",
    "bow on head",
    "joker hat",
    "ribbons",
    "headphones",
    "hair accessories",
    "hair bow",
    "hair ribbon",
    "hairband",
    "halo",
    "hood",
    "maid headdress",
    "red japanese oni horns",
    "tiara",
    "cow ears",
    "monkey ears",
    "sheep ears",
];
